hl_tuning/hl_tuning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hl_tuning/main/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('<str:brand>', MainView.as_view(), name='works_for_exact_brand'),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('lk/', LKView.as_view(), name='lk'),
    path('shop/', ShopMainView.as_view(), name='shop_main'),
    path('shop/product/<str:pk>', ProductDetailView.as_view(), name='product_detail'),
    path('shop/add-to-cart/<str:pk>/', AddToCartView.as_view(), name='add_to_cart'),
    path('shop/remove-from-cart/<str:pk>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('shop/change-qty/<str:pk>/', ChangeQTYView.as_view(), name='change_qty'),
    path('cart/', CartView.as_view(), name='cart'),
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    path('products/<str:pk>', ProductDetailView.as_view(), name='product_detail'),
    path('shop/category/<str:pk>/', CategoryView.as_view(), name='category'),
    path('shop/category/<str:category_pk>/<str:subcategory_pk>/', SubcategoryView.as_view(), name='subcategory'),
    path('project/<str:pk>/', ProjectDetailView.as_view(), name='project_detail'),
]

hl_tuning/main/models.py
from django.db import models
import json
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.urls import reverse


User = get_user_model()


def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]


def get_product_url(obj, viewname):
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={'ct_model': ct_model, 'pk': obj.pk})


class MinResolutionErrorException(Exception):
    pass


class MaxResolutionErrorException(Exception):
    pass


class Media(models.Model):

    image = models.ImageField(verbose_name='Изображение')
    work = models.ForeignKey('Work', verbose_name='Проект', on_delete=models.CASCADE, related_name='related_media')

    def __str__(self):
        return str(self.image.url)


class Service(models.Model):

    name = models.CharField(max_length=255, verbose_name='Название услуги')
    works = models.ManyToManyField('Work', blank=True, related_name='related_service', verbose_name='Работы')

    def __str__(self):
        return self.name


class Brand(models.Model):

    name = models.CharField(max_length=255, verbose_name='Марка')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('brand_detail', kwargs={'pk': self.pk})

    @property
    def products(self):
        return json.dumps(Work.objects.filter(brand=self).values())

    class Meta:
        verbose_name = 'Марка'
        verbose_name_plural = 'Марки'


class Work(models.Model):

    title = models.CharField(max_length=255, verbose_name='Заголовок')
    subtitle = models.CharField(max_length=255, blank=True, verbose_name='Подзаголовок')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, null=True, verbose_name='Марка автомобиля')
    description = models.TextField(verbose_name='Описание', null=True)
    services = models.ManyToManyField(Service, blank=True, related_name='related_work', verbose_name='Услуги')

    def __str__(self):
        return self.title

    @property
    def media_for_main_page(self):
        if not Media.objects.filter(work=self):
            return
        return Media.objects.filter(work=self).first().image.url

    @property
    def media_for_detail(self):
        if not Media.objects.filter(work=self):
            return
        return Media.objects.filter(work=self)

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'


class Category(models.Model):

    name = models.CharField(max_length=255, verbose_name='Имя категории')
    image = models.ImageField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'pk': self.pk})

    @property
    def products(self):
        return json.dumps(Product.objects.filter(category=self).values())

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Subcategory(models.Model):

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    name = models.CharField(max_length=255, verbose_name='Имя подкатегории')
    image = models.ImageField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'


class Product(models.Model):

    MIN_RESOLUTION = (400, 400)
    MAX_RESOLUTION = (800, 800)

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, verbose_name='Подкатегория', blank=True, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=255, verbose_name='Наименование')
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание', blank=True)
    characteristics = models.TextField(verbose_name='Характеристики', blank=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')
    recommended_products = models.ManyToManyField('self', blank=True, related_name='related_product_for_recommendations', verbose_name='Рекомендованные продукты')
    works = models.ManyToManyField(Work, blank=True, related_name='related_product', verbose_name='Примеры установки')
    views = models.PositiveIntegerField(default=0, verbose_name='Просмотры')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class CartProduct(models.Model):

    user = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    qty = models.PositiveIntegerField(default=1, verbose_name='Количество товара')
    product = models.ForeignKey(Product, verbose_name='Товар', on_delete=models.CASCADE)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')

    def __str__(self):
        return "Продукт {} (для корзины)".format(self.product.title)

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.product.price
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Товар в корзине'
        verbose_name_plural = 'Товары в корзине'


class Cart(models.Model):

    owner = models.ForeignKey('Customer', null=True, verbose_name='Владелец', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name='Общая цена')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'


class Customer(models.Model):

    user = models.OneToOneField(User, verbose_name='Пользователь', on_delete=models.CASCADE, default=True)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адрес', null=True, blank=True)
    city = models.CharField(max_length=255, verbose_name='Город', null=True, blank=True)
    index = models.CharField(max_length=255, verbose_name='Индекс', null=True, blank=True)
    orders = models.ManyToManyField('Order', verbose_name='Заказы покупателя', related_name='related_customer', blank=True)

    def __str__(self):
        if not (self.user.first_name and self.user.last_name):
            return self.user.username
        return "Покупатель {} {}".format(self.user.first_name, self.user.last_name)

    class Meta:
        verbose_name = 'Покупатель'
        verbose_name_plural = 'Покупатели'


class Order(models.Model):

    STATUS_NEW = 'new'
    STATUS_PAYED = 'payed'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    PAYING_TYPE_CASH = 'cash'
    PAYING_TYPE_CARD = 'card'
    PAYING_TYPE_ONLINE = 'online'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Новый заказ'),
        (STATUS_PAYED, 'Заказ оплачен'),
        (STATUS_IN_PROGRESS, 'Заказ в обработке'),
        (STATUS_READY, 'Заказ готов'),
        (STATUS_COMPLETED, 'Заказ выполнен')
    )

    DELIVERY_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Самовывоз'),
        (BUYING_TYPE_DELIVERY, 'Доставка')
    )

    PAYING_TYPE_CHOICES = (
        (PAYING_TYPE_CASH, 'Наличными'),
        (PAYING_TYPE_CARD, 'Картой'),
        (PAYING_TYPE_ONLINE, 'Онлайн'),
    )

    customer = models.ForeignKey(Customer, verbose_name='Покупатель', related_name='related_orders', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=1024, verbose_name='Адрес', null=True, blank=True)
    city = models.CharField(max_length=55, verbose_name='Город', null=True, blank=True)
    status = models.CharField(
        max_length=100,
        verbose_name='Статус заказ',
        choices=STATUS_CHOICES,
        default=STATUS_NEW
    )
    buying_type = models.CharField(
        max_length=100,
        verbose_name='Тип заказа',
        choices=DELIVERY_TYPE_CHOICES,
        default=BUYING_TYPE_SELF
    )
    paying_type = models.CharField(
        max_length=100,
        verbose_name='Способ оплаты',
        choices=PAYING_TYPE_CHOICES,
        default=PAYING_TYPE_CASH
    )
    comment = models.TextField(verbose_name='Комментарий к заказу', null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

hl_tuning/main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

from .models import Order


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = (
            'first_name', 'phone', 'city', 'address', 'buying_type', 'comment'
        )


class LoginForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print(self.fields)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Пользователь {username} не найден')
        user = User.objects.filter(username=username).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError('Неверный пароль')
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password']


class SignUpForm(forms.ModelForm):

    confirm_password = forms.CharField(widget=forms.PasswordInput)
    password = forms.CharField(widget=forms.PasswordInput)
    phone = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'
        self.fields['confirm_password'].label = 'Подтвердите пароль'
        self.fields['phone'].label = 'Номер телефона'
        self.fields['first_name'].label = 'Имя'

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Имя {username} занято')
        return username

    def clean(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('Пароли не совпадпают')
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password', 'confirm_password', 'first_name', 'phone']


class LKForm(forms.ModelForm):

    phone = forms.CharField(required=False)
    city = forms.CharField(required=False)
    address = forms.CharField(required=False)
    index = forms.CharField(required=False)
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['phone'].label = 'Номер телефона'
        self.fields['first_name'].label = 'Имя'
        self.fields['city'].label = 'Город'
        self.fields['address'].label = 'Адрес'
        self.fields['index'].label = 'Индекс'
        self.fields['email'].label = 'email'

    class Meta:
        model = User
        fields = ['first_name', 'email', 'phone', 'city', 'address', 'index']

hl_tuning/main/templates/cart.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block headers %}
<link rel="stylesheet" href="{% static 'css/cart.css' %}"/>
{% endblock headers %}

{% block content %}
<section>
    <h3 class="text-center mt-5 mb-5">Ваша корзина {% if not cart.products.count %}пуста{% endif %}</h3>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
    {% if cart.products.count %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Наименование</th>
            <th scope="col">Изображение</th>
            <th scope="col">Цена</th>
            <th scope="col">Кол-во</th>
            <th scope="col">Общая цена</th>
            <th scope="col">Удалить</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart.products.all %}
        <tr>
            <th scope="row">{{ item.product.title }}</th>
            <td><img src="{{ item.product.image.url }}" class="img-fluid"></td>
            <td>{{ item.product.price }} руб.</td>
            <td>
                <form id="qty-change-{{item.product.pk}}" action="{% url 'change_qty' pk=item.product.pk %}"
                      method="POST">
                    {% csrf_token %}
                    <input type="number" class="form-control" name="qty" style="width: 70px;" min="1"
                           value="{{ item.qty }}">
                </form>
                <script>
                    const qtyChange = document.getElementById('qty-change-{{item.product.pk}}')
                    const qtyChangeInput = qtyChange.querySelector('input')
                    qtyChange.onchange = (ev) => {
                        console.log('here')
                        let qty = ev.target.value
                        console.log(qty)
                        qtyChange.submit()
                    }
                </script>
            </td>
            <td>{{ item.final_price }} руб.</td>
            <td>
                <a href="{% url 'delete_from_cart' pk=item.product.pk %}">
                    <button class="btn btn-danger">Удалить из корзины</button>
                </a>
            </td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="2"></td>
            <td>Итого:</td>
            <td>{{ cart.total_products }}</td>
            <td><strong>{{ cart.final_price }} руб.</strong></td>
        </tr>
        </tbody>
    </table>
    <h3 class="text-center mt-5 mb-5">Форма заказа</h3>
    <form action="{% url 'make_order' %}" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-success btn-block mb-3" values="Оформить заказ">
    </form>
</section>
{% endif %}
{% endblock content %}

hl_tuning/main/templates/category_detail.html
{% extends 'base.html' %}

{% block headers %}
{% load static %}
<link rel="stylesheet" href="{% static 'shop/style.css' %}"/>
{% endblock %}

{% block content %}
<section id="categories">
    <div class="category-list">
        {% for category in categories %}
        <h4><a href="{% url 'category' pk=current_category.pk %}"><span></span>{{ category.name }}</a></h4>
        {% if current_category == category %}
        {% for subcategory in subcategories %}
        <h5><a href="{% url 'subcategory' category_pk=current_category.pk subcategory_pk=subcategory.pk %}">{{ subcategory.name }}</a></h5>
        {% endfor %}
        {% endif %}
        {% endfor %}
    </div>
    <div class="container">
        <div class="categories">
            {% for subcategory in subcategories %}
            <div class="box">
                <div class="bg" style="background-image: url({{ subcategory.image.url }});"></div>
                <a href="{% url 'subcategory' category_pk=current_category.pk subcategory_pk=subcategory.pk %}">
                    <h3>{{ subcategory.name }}</h3>
                </a>
            </div>
            {% endfor %}
        </div>
        <div class="products">
            {% for product in products %}
            <h4>{{product.title}}</h4>
            {% endfor %}
        </div>
    </div>
</section>
<script src="{% static 'main/script.js' %}"></script>
{% endblock %}

hl_tuning/main/templates/lk.html
{% extends 'base.html' %}

{% block headers %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/lk.css' %}"/>
{% endblock %}

{% block content %}
    <section class="u-align-center u-clearfix u-custom-color-2 u-section-1" id="carousel_d347">
      <div class="u-clearfix u-sheet u-sheet-1">
        <h2 class="u-text u-text-1">{% if user.first_name %} {{ user.first_name }} {% else %} {{ user.username }} {% endif %}</h2>
        <div class="u-form u-form-1">
          <form action="" method="POST" class="u-clearfix u-form-spacing-15 u-form-vertical u-inner-form" style="padding: 0;" source="custom" name="form">
            {% csrf_token %}
            <div class="u-form-group u-form-name u-form-partition-factor-2 u-form-group-1">
              <label for="id_first_name" class="u-label u-label-1">Имя</label>
              {{ form.first_name }}
            </div>
            <div class="u-form-email u-form-group u-form-group-2">
              <label for="id_email" class="u-label u-label-2">E-mail</label>
              {{ form.email }}
            </div>
            <div class="u-form-group u-form-phone u-form-group-3">
              <label for="id_phone" class="u-label u-label-3">Телефон</label>
              {{ form.phone }}
            </div>
            <div class="u-form-group u-form-group-4">
              <label for="id_city" class="u-label u-label-4">Город</label>
              {{ form.city }}
            </div>
            <div class="u-form-group u-form-group-5">
              <label for="id_address" class="u-label u-label-5">Адрес доставки</label>
              {{ form.address }}
            </div>
            <div class="u-form-group u-form-group-6">
              <label for="id_index" class="u-label u-label-6">Индекс</label>
              {{ form.index }}
            </div>
            <div class="u-align-center u-form-group u-form-submit u-form-group-7">
              <input type="submit" value="Сохранить" class="submit"/>
            </div>
          </form>
        </div>
      </div>
    </section>
    <section class="u-clearfix u-custom-color-1 u-section-2" id="sec-1761">
      <div class="u-clearfix u-sheet u-sheet-1">
        <h3 class="u-text u-text-default u-text-1">История заказов</h3><!--blog--><!--blog_options_json--><!--{"type":"Recent","source":"","tags":"","count":""}--><!--/blog_options_json-->
        <div class="u-blog u-container-style u-expanded-width u-layout-horizontal u-blog-1">
          <div class="u-list-control"></div>
          <div class="u-repeater u-repeater-1"><!--blog_post-->
            <div class="u-blog-post u-container-style u-repeater-item">
              <div class="u-container-layout u-similar-container u-container-layout-1"><!--blog_post_header-->
                <h2 class="u-blog-control u-text u-text-2">
                  <a class="u-post-header-link" href="blog/пост.html"><!--blog_post_header_content-->Заголовок 1-го поста<!--/blog_post_header_content--></a>
                </h2><!--/blog_post_header--><!--blog_post_content-->
                <div class="u-blog-control u-post-content u-text u-text-3"><!--blog_post_content_content-->Пример короткого текста. Lorem ipsum dolor sit amet.<!--/blog_post_content_content--></div><!--/blog_post_content-->
              </div>
            </div><!--/blog_post--><!--blog_post-->
            <div class="u-blog-post u-container-style u-repeater-item">
              <div class="u-container-layout u-similar-container u-container-layout-2"><!--blog_post_header-->
                <h2 class="u-blog-control u-text u-text-4">
                  <a class="u-post-header-link" href="blog/пост-1.html"><!--blog_post_header_content-->Заголовок 2-го поста<!--/blog_post_header_content--></a>
                </h2><!--/blog_post_header--><!--blog_post_content-->
                <div class="u-blog-control u-post-content u-text u-text-5"><!--blog_post_content_content-->Пример короткого текста. Lorem ipsum dolor sit amet.<!--/blog_post_content_content--></div><!--/blog_post_content-->
              </div>
            </div><!--/blog_post--><!--blog_post-->
            <div class="u-blog-post u-container-style u-repeater-item">
              <div class="u-container-layout u-similar-container u-container-layout-3"><!--blog_post_header-->
                <h2 class="u-blog-control u-text u-text-6">
                  <a class="u-post-header-link" href="blog/пост-2.html"><!--blog_post_header_content-->Заголовок 3-го поста<!--/blog_post_header_content--></a>
                </h2><!--/blog_post_header--><!--blog_post_content-->
                <div class="u-blog-control u-post-content u-text u-text-7"><!--blog_post_content_content-->Пример короткого текста. Lorem ipsum dolor sit amet.<!--/blog_post_content_content--></div><!--/blog_post_content-->
              </div>
            </div><!--/blog_post--><!--blog_post-->
            <div class="u-blog-post u-container-style u-repeater-item">
              <div class="u-container-layout u-similar-container u-container-layout-4"><!--blog_post_header-->
                <h2 class="u-blog-control u-text u-text-8">
                  <a class="u-post-header-link" href="blog/пост-3.html"><!--blog_post_header_content-->Заголовок 4-го поста<!--/blog_post_header_content--></a>
                </h2><!--/blog_post_header--><!--blog_post_content-->
                <div class="u-blog-control u-post-content u-text u-text-9"><!--blog_post_content_content-->Пример короткого текста. Lorem ipsum dolor sit amet.<!--/blog_post_content_content--></div><!--/blog_post_content-->
              </div>
            </div><!--/blog_post-->
          </div>
          <div class="u-list-control"></div>
          <a class="u-absolute-vcenter u-gallery-nav u-gallery-nav-prev u-grey-70 u-icon-circle u-opacity u-opacity-70 u-spacing-10 u-text-white u-gallery-nav-1" href="#" role="button">
            <span aria-hidden="true">
              <svg viewBox="0 0 451.847 451.847"><path d="M97.141,225.92c0-8.095,3.091-16.192,9.259-22.366L300.689,9.27c12.359-12.359,32.397-12.359,44.751,0
c12.354,12.354,12.354,32.388,0,44.748L173.525,225.92l171.903,171.909c12.354,12.354,12.354,32.391,0,44.744
c-12.354,12.365-32.386,12.365-44.745,0l-194.29-194.281C100.226,242.115,97.141,234.018,97.141,225.92z"></path></svg>
            </span>
            <span class="sr-only">
              <svg viewBox="0 0 451.847 451.847"><path d="M97.141,225.92c0-8.095,3.091-16.192,9.259-22.366L300.689,9.27c12.359-12.359,32.397-12.359,44.751,0
c12.354,12.354,12.354,32.388,0,44.748L173.525,225.92l171.903,171.909c12.354,12.354,12.354,32.391,0,44.744
c-12.354,12.365-32.386,12.365-44.745,0l-194.29-194.281C100.226,242.115,97.141,234.018,97.141,225.92z"></path></svg>
            </span>
          </a>
          <a class="u-absolute-vcenter u-gallery-nav u-gallery-nav-next u-grey-70 u-icon-circle u-opacity u-opacity-70 u-spacing-10 u-text-white u-gallery-nav-2" href="#" role="button">
            <span aria-hidden="true">
              <svg viewBox="0 0 451.846 451.847"><path d="M345.441,248.292L151.154,442.573c-12.359,12.365-32.397,12.365-44.75,0c-12.354-12.354-12.354-32.391,0-44.744
L278.318,225.92L106.409,54.017c-12.354-12.359-12.354-32.394,0-44.748c12.354-12.359,32.391-12.359,44.75,0l194.287,194.284
c6.177,6.18,9.262,14.271,9.262,22.366C354.708,234.018,351.617,242.115,345.441,248.292z"></path></svg>
            </span>
            <span class="sr-only">
              <svg viewBox="0 0 451.846 451.847"><path d="M345.441,248.292L151.154,442.573c-12.359,12.365-32.397,12.365-44.75,0c-12.354-12.354-12.354-32.391,0-44.744
L278.318,225.92L106.409,54.017c-12.354-12.359-12.354-32.394,0-44.748c12.354-12.359,32.391-12.359,44.75,0l194.287,194.284
c6.177,6.18,9.262,14.271,9.262,22.366C354.708,234.018,351.617,242.115,345.441,248.292z"></path></svg>
            </span>
          </a>
        </div>
      </div>
    </section>
  </body>
</html>
{% endblock %}

hl_tuning/main/templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block headers %}
{% load static %}
<link rel="stylesheet" href="{% static 'main/login.css' %}">
{% endblock %}

{% block content %}
<section style="height: 110vh;">
    <div class="imgBx">
        <img src="{% static 'main/bmw-bg.jpg' %}" alt=""/>
    </div>
    <div class="contentBx">
        <div class="formBx">
            <h3>Регистрация</h3>
            <form action="" method="POST">
            {% csrf_token %}
            <div class="inputBx">
                <span>Логин</span>
                <input type="text" name="username" maxlength="150" class="" required id="id_username"/>
            </div>
            <div class="inputBx">
                <span>Пароль</span>
                <input type="password" name="password" maxlength="150" class="" required id="id_password"/>
            </div>
            <div class="inputBx">
                <span>Подтвердите пароль</span>
                <input type="password" name="confirm_password" maxlength="150" class="" required id="id_confirm_password"/>
            </div>
            <div class="inputBx">
                <span>Телефон</span>
                <input type="text" name="phone" maxlength="150" class="" id="id_phone"/>
            </div>
            <div class="inputBx">
                <input type="submit" class="btn btn-success" value="Зарегистрироваться"/>
            </div>
            <div class="inputBx">
                <p>Уже есть аккаунт? <a href="{% url 'login' %}">Войти</a></p>
            </div>
        </form>
        <h4>Войдите через социальные сети</h4>
        <ul class="sci">
            <li><img src="{% static 'main/vk.png' %}" alt=""></li>
            <li><img src="{% static 'main/instagram.png' %}" alt=""></li>
            <li><img src="{% static 'main/google-glass-logo.png' %}" alt=""></li>
        </ul>
        </div>
    </div>
</section>
{% endblock %}